version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4237:3000
    volumes:
      - .:/app
      - next:/app/.next
      - /app/node_modules

volumes:
  next:
